---
- name: Create Elasticsearch directory
  file:
    path: /home/{{ default_user }}/{{ CONTAINER_NAME }}/certificates/
    state: directory
    mode: 0755

- name: Elasticsearch Data Volume
  docker_volume:
    name: "{{ CONTAINER_NAME }}_data"
    state: present

- name: ES config file
  template:
    src: elasticsearch.yml.j2
    dest: /home/{{ default_user }}/{{ CONTAINER_NAME }}/elasticsearch.yml
    mode: 0644

- name: Elasticsearch
  docker_container:
    name: "{{ CONTAINER_NAME }}"
    hostname: "{{ HOSTNAME }}"
    image: "{{ IMAGE }}:{{ BUILD }}"
    pull: "true"
    env:
      ES_JAVA_OPTS: "-Djava.net.preferIPv4Stack=true -Xms{{ ES_HEAP_SIZE }} -Xmx{{ ES_HEAP_SIZE }}"
      ELASTIC_PASSWORD: "{{ ADMIN_PASSWORD }}"
    network_mode: "{{ DOCKER_NETWORK_MODE }}"
    cpu_period: "{{ DOCKER_CPU_PERIOD }}"
    cpu_quota: "{{ DOCKER_CPU_QUOTA }}"
    memory: "{{ DOCKER_MEMORY }}"
    recreate: "yes"
    state: "started"
    log_driver: "{{ DOCKER_LOG_DRIVER }}"
    log_options: "{{ DOCKER_LOG_OPTIONS }}"
    restart_policy: "unless-stopped"
    published_ports:
      - "0.0.0.0:9200:9200"
      - "0.0.0.0:9300:9300"
    volumes:
      - "{{ CONTAINER_NAME }}_data:/usr/share/elasticsearch/data"
      - /home/{{ default_user }}/{{ CONTAINER_NAME }}/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - /home/{{ default_user }}/{{ CONTAINER_NAME }}/certificates/:/usr/share/elasticsearch/config/certificates
    labels:
      "{{ DOCKER_LABELS }}"

